import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Providers from './components/ui/Providers'
import Appbar from './components/appbar/Appbar'
import { getServerSession } from 'next-auth'
import { authOptions } from './api/auth/[...nextauth]/lib/auth'
import prisma from './api/prisma/prisma'
import { createCart } from './actions'
import CartSidebar from './components/cart/CartSidebar'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const session =  await getServerSession(authOptions)
  let cart = null
  if (session){
  cart = await prisma.cart.findUnique({
    where:{
      userId:session.user.id
    }, include:{
      products:true
    }
  })}
  if (session && !cart) {
    cart = await createCart(session.user.id)
  }
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers session={session} dbCart={cart}>
          <Appbar />
          <CartSidebar />
          {children}
        </Providers>
      </body>
    </html>
  )
}
